### ISSUE TITLE
New versions of chrome blocking response 

### ISSUE THREAD

**Issue by c01gat3** [horans/pardot-form-ajax-handler#1]
After submitting the form, I receive an error in the console: "Cross-Origin Read Blocking (CORB) blocked cross-origin response..."

Is this an issue only Salesforce/Pardot can fix, or is there a workaround you can apply?

https://chromestatus.com/feature/5629709824032768
https://www.chromium.org/Home/chromium-security/corb-for-developers/

**Comment by horans** [comment]
Had a test run on basic demo: https://horans.github.io/pardot-form-ajax-handler/demo/demo-basic.html
Chrome 108, Edge 107, Firefox 107, all work just fine.

CORB is something to do with your server side config.
Do you have `response.addHeader("X-Content-Type-Options", "nosniff");` or incorrect content type for javascript files?

```php
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/javascript');
```

**Comment by c01gat3** [comment]
Thanks for the quick response!

I found the issue.

In the form handler, "Enable data forwarding to the success location" had been checked on. This resulted in the success url to have all the form values included in a query string - which is why Chrome decided to block it. I don't need the values in the response, so unchecking that box in Pardot resolved it.

Love your work - thank you!
